### ISSUE TITLE
How to generate conformations

### ISSUE THREAD

**Issue by peastman** [openmm/qmdataset#2]
We need to decide how to generate conformations for each molecule.  We want a diverse set for each one, and we want to include both low energy and high energy conformations (keeping in mind that low energy for an MD force field might not be low energy for QM).  We also want this to be fast.  If selecting the conformations takes as long as doing the final computations, that will waste much of our computing budget.

Here is an initial proposal.

1. Run high temperature MD and keep some fixed number (say 25) of conformations drawn from the trajectory.  For the very small molecules we'll be working with, 1 ns at 500K should be plenty, possibly excessive.
2. For each of those conformations, do a few minimization steps with a fast QM method to create a nearby lower energy conformation.

What method should we use for the minimization?  Preferably it should be something very fast, e.g. semiempirical.

**Comment by davidlmobley** [comment]
Diverse conformers should be a good contribution.

(This is a very interesting thread.)

**Comment by SimonBoothroyd** [comment]
> That does help increase the overall diversity. Ok, so modify step 1 to

This is what I was thinking as well - good to see that it helps!

> How many iterations of minimization should we perform? Each iteration is a line minimization, not just a single step, so the energy goes down quickly.

It would be interesting to see the spread if we just i) took each diverse 500K conformer ii) ran a v. short simulation at 298K and took this conformer, and iii) do a full L-BFGS minimization so 3 conformers per each step 2) conformer.

It may also be good to add a step 5) where you do a quick round of pruning based on the final RMSD matrix to handle the cases where the 'diverse' high energy conformers have minimised / quenched to the same / very similar minima.

**Comment by peastman** [comment]
> It may also be good to add a step 5) where you do a quick round of pruning based on the final RMSD matrix to handle the cases where the 'diverse' high energy conformers have minimised / quenched to the same / very similar minima.

I also thought about that.  If we were fully minimizing the conformations that would be important, since you could easily get two converging to the same minimum.  But if we're only doing 2 or 3 iterations of minimization I don't think it's necessary.  They'll still be different from each other.  And if several states all converge toward the same minimum, that suggests it's a place where simulations will spend a lot of time.  Having multiple samples in the area surrounding that minimum is a good thing.

**Comment by peastman** [comment]
I've been running experiments with the molecules in #5 to see how well this system works at generating diverse conformations.  For the 25 high energy conformations it works quite well, with typical RMSD between conformations of around 3 A.  I'm less sure about the energy minimization, mostly because I'm just not sure what's a good metric.

Three iterations of minimization has only a tiny effect on the coordinates.  RMSD from the original conformation is typically only about 0.04 A.  On the other hand, that still has a huge effect on the forces and energy.  The average force magnitude is around 3x smaller.  So it moves a very short distance in a steeply downhill direction, leading to a much lower energy conformation.  Is that good or bad?  I'm really not sure.

Another option is to follow up the minimization with a bit more MD, but at much lower temperature.  If I run 1 ps at 100K, the RMSD goes up to around  1 A and the average force magnitude is still about 2-3x smaller than before minimizing.  Possibly that will be more useful for sampling the energy surface?

**Comment by peastman** [comment]
Closing since version 1 is now released.
