### ISSUE TITLE
Name for this dataset

### ISSUE THREAD

**Issue by peastman** [openmm/qmdataset#9]
We should come up with a catchy name.  Make your suggestions, the more the better, and don't be afraid to be silly!

**Comment by peastman** [comment]
Very catchy!

**Comment by peastman** [comment]
We also could capitalize SPICE and pretend it's an acronym for "Small-molecule/Protein Interaction Chemical Energies".  I bet people would even believe it.

**Comment by peastman** [comment]
Does anyone else have thoughts on this?

@pavankum, is deciding on a name blocking you from setting up the calculations?  If so, we really need to come up with something.

**Comment by pavankum** [comment]
@peastman I am still waiting on a release from qcfractal which resolves [this](https://github.com/MolSSI/QCFractal/issues/688), the fix is in there. Also, a new qcsubmit release with the new [hdf5 functionality](https://github.com/openforcefield/openff-qcsubmit/commit/627755b2c17a53d4eef9ca0c0386e38ae660d06f). Once they're merged I can work on pushing the submission PR.

**Comment by peastman** [comment]
Ok, good to know.  Thanks.

But we still need to pick a name!

**Comment by jchodera** [comment]
We'll need to take a few stabs at this, so I'd suggest keeping in mind we'll have version numbers and different compositional variants.

Longer descriptive names are also most useful for these QM datasets. The ML models we build from them can have catchier names.

Each thematically-related subset should also likely have its own name, such as 
* `OpenMM - DES370K dimers - v1`
* `OpenMM - dipeptides - v1`
* `OpenMM - solvated amino acids - v1`

By the way, didn't we want to add the _monomers_ from the DES370K set as well? I don't think we've done that yet, but this will be critical for building good models, won't it?

**Comment by peastman** [comment]
> Is there a reason OpenQM is a poor choice?

It would be a good name for a piece of software that does QM calculations.  For a database of chemical energies, I'm not as sure.  A name like "ANI" doesn't suggest any meaning at all, so you can use it for anything.  A name like "OpenQM" does suggest a meaning.  When people see the name, will they assume it refers to something different from what it actually is?

It's still better than Piña Colada though. :)

**Comment by peastman** [comment]
@pavankum has declared that SPICE is the name!  That means we can close this.
